version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: complaint-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: complaintdb
      POSTGRES_USER: complaint_user
      POSTGRES_PASSWORD: complaint_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
